---
- name: Deploy application
  hosts: all
  become: no
  vars:
    deploy_date: "{{ '%04d%02d%02d' | format(ansible_date_time.year | int, ansible_date_time.month | int, ansible_date_time.day | int) }}"
    deploy_user: "{{ ansible_user | default('newbie') }}"
    deploy_path: "/usr/share/nginx/html/jenkins/{{ ansible_user_folder | default('manhg2') }}"
    template_path: "/usr/share/nginx/html/jenkins/template2"
    project_folder: "web-performance-project1-initial"
    deploy_folder: "{{ deploy_path }}/deploy/{{ deploy_date }}"
    max_releases: 5

  tasks:
    - name: Debug paths
      debug:
        msg: |
          Template path: {{ template_path }}
          Deploy path: {{ deploy_path }}
          Project folder: {{ project_folder }}
          Deploy folder: {{ deploy_folder }}
    - name: Check if user directory exists
      stat:
        path: "{{ deploy_path }}"
      register: user_dir_stat

    - name: Create user directory if not exists
      file:
        path: "{{ deploy_path }}"
        state: directory
        mode: '0755'
        owner: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"
        group: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"
      when: not user_dir_stat.stat.exists

    - name: Create project directory
      file:
        path: "{{ deploy_path }}/{{ project_folder }}"
        state: directory
        mode: '0755'
        owner: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"
        group: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"

    - name: Create deploy directory structure
      file:
        path: "{{ deploy_path }}/deploy"
        state: directory
        mode: '0755'
        owner: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"
        group: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"

    - name: Copy template to project directory
      copy:
        src: "{{ template_path }}/"
        dest: "{{ deploy_path }}/{{ project_folder }}"
        mode: '0755'
        owner: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"
        group: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"
      register: template_copy_result

    - name: Debug template copy result
      debug:
        var: template_copy_result

    - name: Create deploy directory
      file:
        path: "{{ deploy_folder }}"
        state: directory
        mode: '0755'
        owner: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"
        group: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"

    - name: Copy index.html
      copy:
        src: "{{ template_path }}/index.html"
        dest: "{{ deploy_folder }}/index.html"
        mode: '0644'
        owner: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"
        group: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"

    - name: Copy 404.html
      copy:
        src: "{{ template_path }}/404.html"
        dest: "{{ deploy_folder }}/404.html"
        mode: '0644'
        owner: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"
        group: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"

    - name: Copy css directory
      copy:
        src: "{{ template_path }}/css/"
        dest: "{{ deploy_folder }}/css/"
        mode: '0755'
        owner: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"
        group: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"

    - name: Copy js directory
      copy:
        src: "{{ template_path }}/js/"
        dest: "{{ deploy_folder }}/js/"
        mode: '0755'
        owner: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"
        group: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"

    - name: Copy images directory
      copy:
        src: "{{ template_path }}/images/"
        dest: "{{ deploy_folder }}/images/"
        mode: '0755'
        owner: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"
        group: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"

    - name: Run test script (if exists)
      command: "{{ deploy_path }}/{{ project_folder }}/test/test.sh"
      args:
        chdir: "{{ deploy_path }}/{{ project_folder }}"
      register: test_result
      failed_when: test_result.rc != 0
      ignore_errors: true

    - name: Create symlink to current
      file:
        src: "{{ deploy_folder }}"
        dest: "{{ deploy_path }}/deploy/current"
        state: link
        owner: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"
        group: "{{ 'newbie' if ansible_connection != 'local' else 'jenkins' }}"

    - name: Get list of release directories
      find:
        paths: "{{ deploy_path }}/deploy"
        patterns: "20*"
        file_type: directory
      register: release_dirs

    - name: Remove old releases (keep only {{ max_releases }})
      file:
        path: "{{ item.path }}"
        state: absent
      when: release_dirs.matched > (max_releases | int)
      loop: "{{ (release_dirs.files | sort(attribute='path', reverse=true))[(max_releases | int):] }}"

    - name: Check nginx status
      service:
        name: nginx
        state: started
      when: ansible_connection != 'local'

    - name: Display deployment info
      debug:
        msg: |
          Deployment completed successfully!
          Date: {{ deploy_date }}
          Project folder: {{ project_folder }}
          Deploy path: {{ deploy_folder }}
          Current symlink: {{ deploy_path }}/deploy/current
