name: Trigger Jenkins Deployment

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Trigger Jenkins Job
      uses: davidbrockman/trigger-jenkins-job@v1
      with:
        jenkins-url: ${{ secrets.JENKINS_URL }}
        jenkins-user: ${{ secrets.JENKINS_USER }}
        jenkins-token: ${{ secrets.JENKINS_TOKEN }}
        job-name: ${{ secrets.JENKINS_JOB_NAME }}
        parameters: |
          BRANCH_NAME=${{ github.ref_name }}
          GIT_COMMIT=${{ github.sha }}
          GIT_URL=${{ github.server_url }}/${{ github.repository }}
          BUILD_CAUSE=github-actions
          
    - name: Wait for Jenkins Job
      uses: davidbrockman/wait-for-jenkins-job@v1
      with:
        jenkins-url: ${{ secrets.JENKINS_URL }}
        jenkins-user: ${{ secrets.JENKINS_USER }}
        jenkins-token: ${{ secrets.JENKINS_TOKEN }}
        job-name: ${{ secrets.JENKINS_JOB_NAME }}
        build-number: ${{ steps.trigger-jenkins.outputs.build-number }}
        
    - name: Check Jenkins Job Status
      if: failure()
      run: |
        echo "Jenkins job failed or was aborted"
        exit 1
